[mypy]
python_version = 3.11
plugins =
ignore_missing_imports = True
check_untyped_defs = True
warn_unused_ignores = True
no_implicit_optional = True
strict_optional = True

[mypy-tests.*]
ignore_errors = True
